# Generated by Django 4.2.7 on 2025-11-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.CharField(default='Class 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(default='A', max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='joining_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='specialization',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
